docs/Available-Plug-ins.md
- used the existing format (although imho the links will suit better in a separate line)
- since the order of the list seems random, i put it at second place, because it seems to me like an order of possible interest for end-users
- copied the text-line from https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet resp. https://play.google.com/store/apps/details?id=keepass2android.keepass2android
=> added the lacking KeyboardSwap-plugin

src/keepass2android/PasswordActivity.cs, src/keepass2android/Properties/AndroidManifest_debug.xml, src/keepass2android/Properties/AndroidManifest_light.xml, src/keepass2android/Properties/AndroidManifest_net.xml, src/keepass2android/Properties/AndroidManifest_nonet.xml
Tested it on Marsmallow (6.0).
Probably fixes #258 and maybe parts of #4(haven't tested it).
=> Fix for issue #221

docs/Documentation.md
Changes:
- Changed last bullet in **What you should know and think about** into two bullet points due to change 2.
- Changed MarkDown so it renders correctly on GitHub Parser.
- Changed wording into bullet 2.2 to emphasise storing any second-factor authentication (if any was used).
=> Updated Documentation.md to GitHub-flavoured MarkDown

src/keepass2android/Resources/values/strings.xml
Thanks for adding Nextcloud @PhilippC. 
This PR changes naming as NC is written with lower C.
=> NextCloud -> Nextcloud

docs/README.md
Added the Keepass2Android Logo to README.md to give it a little more "flare" when viewing it on Github.
(This wasn't solicited at all, but I see logos on many GitHub repos and enjoy the look it adds to the readme. I enjoy Keepass2Android alot so I wanted to try and contribute _something_ to the project.)
=> Added Logo to README.md

src/keepass2android/services/AutofillBase/Kp2aDigitalAssetLinksDataSource.cs
Also tidy / reorganize `_trustedBrowsers` list somewhat.
Fixes #758.
=> Add support for autofill in Firefox Preview/Fenix

src/keepass2android/CreateDatabaseActivity.cs, src/keepass2android/EntryEditActivity.cs, src/keepass2android/PasswordActivity.cs
=> Restore cursor position after switching password visibility.

src/java/JavaFileStorage/app/build.gradle, src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/WebDavStorage.java
A fix has been pushed here https://github.com/square/okhttp/pull/6295
=> Update OkHttp to 4.10.0-RC1 to remove workaround for #747

src/keepass2android/Resources/values-sr/strings.xml
Made contribution on Serbian translation. Keep up the good work with the app! :) 
P.S. I would appreciate if you add "hacktoberfest-accepted" label to PR, thanks.
=> Serbian translation

docs/README.md
I just stumbled across this and thought, that this link might have been dead for a while now :smile:
=> Remove Google+ group from readme

.github/workflows/build.yml, .gitignore, Makefile, docs/Build.readme.md
=> Build system improvements (Makefile, github workflow)

src/keepass2android/services/CopyToClipboardService.cs
=> Suppress "Entry is available" notifications on wearable devices

docs/Build.readme.md
Add notes to build documentation based on findings from issue #2211
=> Update build documentation

src/java/JavaFileStorage/settings.gradle
Resolve issue where AS fails to import Android API jar classes
=> Get JavaFileStorage working in Android Studio

src/keepass2android/Totp/TrayTotpPluginAdapter.cs
closes https://github.com/PhilippC/keepass2android/issues/2458
=> make settings field for TrayTotp style otp entries optional

src/keepass2android/Totp/Keepass2TotpPluginAdapter.cs
=> replace base32 parsing algorithm to fix issue with some TOTP entries using KeePass2 style

src/keepass2android/EntryActivity.cs
=> copy text value to clipboard when long-clicking in Entry view

src/keepass2android/settings/AutofillDisabledQueriesPreference.cs
closes https://github.com/PhilippC/keepass2android/issues/1942
=> Fix bad text color on autofill target preference dialog

src/Kp2aBusinessLogic/database/edit/AddEntry.cs
=> fix: number of entries in group did not immediately update 

.github/workflows/build.yml
Used wrong one earlier, fixing that
=> Use the right branch name

src/keepass2android-app/SelectStorageLocationActivity.cs
=> add a theme to SelectStorageLocationActivity

src/keepass2android-app/Manifests/AndroidManifest_debug.xml, src/keepass2android-app/Manifests/AndroidManifest_net.xml, src/keepass2android-app/Manifests/AndroidManifest_nonet.xml, src/keepass2android-app/SelectCurrentDbActivity.cs
=> Add support for otpauth:// URIs

src/Kp2aBusinessLogic/Io/OneDrive2FileStorage.cs
this change fixes an issue with OneDrive: sometimes, the wrong DriveId was used to list the user's shares which was leading to an empty file browser screen. Also, files can be used if they are shared directly (not the parent folder)
Related to https://github.com/PhilippC/keepass2android/issues/2794
=> Improve OneDrive implementation

src/keepass2android-app/PasswordActivity.cs
=> Fix crash when combining biometric unlock and KeeChallenge/OTP.

src/keepass2android-app/KeeChallenge.cs
=> fix implementation of yubikey secret reading

src/keepass2android-app/FileSelectHelper.cs
=> Make dialogs for SFTP, FTP, Mega, WebDav and Nextcloud not cancelable
