PhilippC/keepass2android

- src/JavaFileStorageBindings/Jars/adal-1.1.19/res/layout/http_auth_dialog.xml
- src/java/JavaFileStorageTest-AS/app/src/main/res/layout/sftp_credentials.xml
- src/java/JavaFileStorageTest-AS/app/src/main/res/layout/webdav_credentials.xml
Due to recent attacks, malicious apps that are using the accessibility service can capture all user inputs. In this case, the passwords should be ignored for the accessibility service, so such attacks cannot happen. This is done by our research project in CISPA, Saarland University, Germany.
> Password should be invisible to the accessibility services

- src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/PCloudFileStorage.java
As advised in https://github.com/PhilippC/keepass2android/pull/523#issuecomment-416719538
Also consider error 2095 as a logout, so that the user can re-login.
> Implement requiresSetup for PCloud.

- crowdin.yml
The crowdin automation now is not friendly for Chinese. I found that zh-CN and zh-TW wrote into same zh file.
For better Chinese translation, zh-CN is used for whole zh because Simplified Chinese is the most used.
And zh-TW should be zh-rTW and zh-rHK for most Traditional Chinese users.
Details can be found here: https://medium.com/fabiohub/chinese-locale-in-android-part-2-d1cfe87b3fb2
The summary of the article is below.
> In order to support Chinese for both before & after Android 7.0 devices, the minimum resources needed to maintain will be:
> 
>     en (English)
>     zh-rHK (Traditional Chinese)
>     zh-rTW (Traditional Chinese)
>     zh (Simplified Chinese)
About cloning the zh-TW to zh-rTW and zh-rHK, I emailed Crowdin Support Team for a answer after I didn't find any methods for …
> Update crowdin.yml for better Chinese localiztion

- src/keepass2android/Properties/AndroidManifest_debug.xml
- src/keepass2android/Properties/AndroidManifest_net.xml
- src/keepass2android/Properties/AndroidManifest_nonet.xml
For your information, there are other issues that prevent the build from working out of the box on Linux:
- Legacy path to Xamarin in SamsungPass project solution (fixed in this stalled PR: https://github.com/PhilippC/Xamarin-Samsung-Pass/pull/1)
- ARME ABI support was dropped in recent NDK versions and I didn't want to downgrade. See [this patch](https://gist.github.com/gilbsgilbs/4fc996d4c454ca19ec6a6c34610531c5) that drops support in KP2A. You may want to apply it at some point.
Otherwise, building under Linux remains possible, but working on Xamarin projects without VS is still very impractical unfortunately. That's what is really preventing me from contributing more actually :disappointed: . I'm done editing huge XML files by hand :smile: .
> Fix invalid namespace in manifests causing build failure on Linux.

- src/keepass2android/services/AutofillBase/Kp2aDigitalAssetLinksDataSource.cs
Added Fenix Nightly and [Reference Browser ](https://github.com/mozilla-mobile/reference-browser/) to the browser whitelist.
Related https://github.com/PhilippC/keepass2android/issues/758
> Add support for Fenix Nightly and Reference Browser

- src/build.readme.md
In my system (OpenSUSE Tumbleweed 20190806 64bit) its path was
"/usr/lib64/libzip.so.5".
> Added a different path to libzip5 in Linux build instructions

- src/build-scripts/build-apk.sh
- src/build-scripts/build-xamarin.sh
If ANDROID_HOME environment variable is set, add parameter "/p:AndroidSdkDirectory=$ANDROID_HOME" to improve the Android SDK detection.
In my system I had to add this parameter to be able to build the app. The environment variable should always be set but to be sure I added a check anyway.
> Improved Android SDK detection in Linux build scripts

- src/keepass2android/PasswordActivity.cs
> Fix “CHANGE DATABAS” button bug

- src/keepass2android/Resources/values-de/strings.xml
Typo in original string: "musst" --> "muss"
Made more specific: "sie" --> "die Datei" ("it" --> "the File")
> Fixes Typo

- src/keepass2android/Resources/xml/autofillservice.xml
Propose adding the Beta and Nightly versions for Brave. I assume prerelease is fair game since Chrome Canary is on there.
> Allow autofill in prerelease Brave browser.

- src/keepass2android/Resources/values-zh/strings.xml
remove redundant space in line break
How to reproduce at  latest (v1.09a-r3)  Keepass2Android:
1. Android system with **Chinese** language
2. Open keepass2android
3. Click Top-Right to `Settings` （设置）
4. Click `About` （关于）
5. Click  `Version history`（版本历史记录）
6. Swipe to Version 1.07
> chore: typo in Chinese  version ChangeLog  v1.07

- src/build.readme.md
This uses the updated CI OSS build link from Xamarin.Android's README.md.
> Fix Xamarin.Android CI build link

- docs/README.md
The current URL displays the following page when opened:
This pull request fixes this issue.
> Fix homepage URL

- Makefile
On Windows, before the start of the java target, processing took ~10sec while less than a second on linux.
Disable built-in rules to speed-up the Makefile processing.
> Speed-up makefile processing:

- src/keepass2android/FingerprintSamsungIdentifier.cs
This permits to fix build failure when running xamarin >= 12.1 (which is the case starting from VS 2022 on windows). There is a sibling PR in samsungpass: https://github.com/PhilippC/Xamarin-Samsung-Pass/pull/3
This commit has to be merged with the commit in SamsungPass submodule that updates SamsungPass to v1.2.6.
Commit message below:
With 1.1.3 build fails as soon as we use Xamarin.Android >= 12.1 (on all platforms) [1].
Actually, this is due the version of r8.jar shipped by Xamarin which now fails. Failure is actually normal [2], as expected, while in the past it didn't fail (problem not catched in older versions).
So the bug is actually in SamsungPass.
This PR has to be taken with caution:
- it was just to check that it would build with a newer version of SamsungPass
- The new …
> Add function to support 'SamsungPass v1.2.6' (fixes build failure)

- src/keepass2android/EntryActivity.cs
- src/keepass2android/EntryActivityClasses/CopyToClipboardPopupMenuIcon.cs
- src/keepass2android/Utils/Util.cs
- src/keepass2android/services/CopyToClipboardService.cs
This is to fix https://github.com/PhilippC/keepass2android/issues/2058
Fix https://github.com/PhilippC/keepass2android/issues/2071
Fix https://github.com/PhilippC/keepass2android/issues/2137
~I wasn't sure if I need to wrap the call to `.Extras` in an api version check >= 24, see [here](https://learn.microsoft.com/en-us/dotnet/api/android.content.clipdescription.extras?view=xamarin-android-sdk-12#android-content-clipdescription-extras), the [copy and paste](https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent) documentation didn't seem to think it was necessary?~ (Check added)
> Mark passwords as sensitive when copy to clipboard

- Makefile
- src/.nuget/packages.config
It references a package that is deprecated and which seem to be already replaced
> remove src/.nuget/packages.config

- .gitignore
- src/Kp2aBusinessLogic/Kp2aBusinessLogic.csproj
- src/TwofishCipher/TwofishCipher.csproj
Default value for `<AndroidResgenFile>` is Resource.designer.cs https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#androidresgenfile
Two projects were using `<AndroidResgenFile>Resources\Resource.Designer.cs</AndroidResgenFile>` All other projects use `<AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>` Difference is one has uppercase D, the other lowercase d
.gitignore already has a rule for 'Resource.designer.cs' in it.
The two projects that were with Resource.Designer.cs needed either a specific line in gitignore or weren't actually ignored.
Selected fix here is to rename the file with a lowercase 'd' instead of uppercase. This permits to remove one line from .gitignore and keep the other file really ignored
> Fix gitignore with Resource.designer.cs/Resource.Designer.cs

- .github/workflows/build.yml
- src/java/KP2ASoftkeyboard_AS/app/build.gradle
Doesn't work on linux because kp2a targets v13.0 which doesn't seem supported by the latest xamarin.android-oss. See https://github.com/xamarin/xamarin-android/issues/7739
Seems you will have to [migrate the project to ".Net Android"  >= 6](https://github.com/xamarin/xamarin-android/wiki/Migrating-Xamarin.Android-Applications-to-.NET-6)  which would permit to build on linux again with android-33.
As per: https://github.com/xamarin/xamarin-android/issues/7235#issuecomment-1206789424
> Unfortunately the Classic OSS Xamarin.Android packages for Linux are no longer being built and as such they are not available for the v13.0 tag.
For the other changes in this PR, see individual commits.
Targeting v12.0 as here would permit to build on linux too: …
> Fix github workflow

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This PR adds issue templates for bug report, feature request, and question to the .github/ISSUE_TEMPLATE directory. The project currently has over 900 open issues, and the addition of these templates will standardize the information provided in issues and make it easier for contributors to provide the necessary information.
The bug report template includes checkboxes to ensure that the FAQ has been checked and open issues have been searched before submitting a new bug report. The feature request template is a simple template for suggesting new ideas for the project. The question template asks for the version of Keepass2Android being used to help with troubleshooting.
Prefixes have been added to issue titles to improve consistency and make it easier to identify the type of issue. This …
> Add issue templates for bug report, feature request, and question

- src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/SftpStorage.java
Since IPv6 addresses contain colons, they break the host:port URI parsing logic, since "host" will have colons in it.
This fix adds URL encoding/decoding of the "host" parameter, thus removing any possible colons in that parameter that could conflict with the host:port separator.
> Bugfix for issue #2350 - SFTP fails to connect to IPv6 address

- src/keepass2android/Utils/Util.cs
- src/keepass2android/settings/DatabaseSettingsActivity.cs
Populate "System language" as a first class item in the language preference list so that users can select it in scenarios where they have previously selected a specific language, and wish to go back to the default.
Fixes bug #2426
> Bug 2426 Add "System language" as language option

- src/keepass2android/Resources/values-de/strings.xml
* Fix grammar in German translation of `TransformingKey`
* Unify German spelling of `keyfile`
* Fix capitalization of [KeePassDroid](https://www.keepassdroid.com/)
> Update strings.xml (German)

- src/keepass2android/PasswordActivity.cs
This PR fixes the issue, where, when selecting master key type "Password + Key file + Challenge-Response for KeePass XC", the master key type would not be remembered after locking the database.
extended "SetKeyProviderFromString()" to set _keyFile for "ChallengeXCKeyFile";
extended "InitializePasswordModeSpinner()" case 7 to remember key file location;
... and therby fixing issue #2160
> remember keyprovider for "Password + Key file + Challenge-Response for KeePass XC" 

- src/Kp2aBusinessLogic/Io/NetFtpFileStorage.cs
Change working directory to target path and call GetListing on current directory instead of calling GetListing on explicit path.
For some reason GetListing(path) does not always return the contents of the directory. However, calling SetWorkingDirectory(path) followed by GetListing(null, options) to list the contents of the working directory does consistently work.
Similar behavior was confirmed using ncftp client. I suspect this is a strange bug/nuance in the server's implementation of the LIST command?
> Bugfix for issue #2423 - FTP contents invisible

- src/keepass2android/app/App.cs
This PR hides the progress dialog (spinner) when a dialog that requests user input appears (such as asking the user if they want to merge changes, or confirming a database reload). The progress dialog will reappear when the user dismisses the dialog, if the in progress task is not already finished. This prevents the app from getting stuck because it is waiting for user input, but the progress dialog covers the user input dialog.
Fixes #1512
> Hide progress dialogs when user input dialog is showing

- src/Kp2aBusinessLogic/Io/JavaFileStorage.cs
- src/Kp2aBusinessLogic/Io/SftpFileStorage.cs
- src/keepass2android/app/App.cs
- src/keepass2android/settings/DatabaseSettingsActivity.cs
This PR fixes an issue introduced with PR #2379 where the UI toggle for SFTP/FTP debugging state is not persisted across app sessions.
> Persist ftp debug preference

- .github/workflows/build.yml
At https://github.com/PhilippC/keepass2android/pull/2692/commits:
Happened to notice, no need to run the same workflow twice in PRs.
Happy holidays!
> Prevent duplicate CI runs in PRs

- src/keepass2android-app/services/AutofillBase/Kp2aDigitalAssetLinksDataSource.cs
This app ID has not been used for a few years now and can be safely removed. 
See the original PR for added context: https://github.com/PhilippC/keepass2android/pull/896
> Remove deprecated Firefox Nightly app ID from trusted browsers

- src/keepass2android-app/EntryActivity.cs
- src/keepass2android-app/LockCloseActivity.cs
- src/keepass2android-app/LockCloseListActivity.cs
- src/keepass2android-app/LockingClosePreferenceActivity.cs
- src/keepass2android-app/Manifests/AndroidManifest_debug.xml
- src/keepass2android-app/Manifests/AndroidManifest_net.xml
- src/keepass2android-app/Manifests/AndroidManifest_nonet.xml
- src/keepass2android-app/PasswordActivity.cs
- src/keepass2android-app/QuickUnlock.cs
- src/keepass2android-app/SelectCurrentDbActivity.cs
- src/keepass2android-app/app/App.cs
- src/keepass2android-app/services/CopyToClipboardService.cs
- src/keepass2android-app/services/OngoingNotificationsService.cs
Exported receivers are required because it is allowed that plugins send intents and also intents from system notifications are not received in NonExported mode.
> upgrade to target sdk 34: mark OngoingNotificationsService as Use, register receivers as exported

- src/Kp2aBusinessLogic/SearchDbHelper.cs
This is an attempt to solve __URL matching too lax__ https://github.com/PhilippC/keepass2android/issues/1926.
Warning: untested  
I am not able to compile the project in my environment.  
At first, I thought the project was a standard Android project (Java/Kotlin). This is as far as I can go.
> Fix hostname matching logic

- src/java/KP2ASoftkeyboard_AS/app/src/main/java/keepass2android/softkeyboard/KP2AKeyboard.java
- src/keepass2android-app/EntryActivity.cs
- src/keepass2android-app/LockCloseActivity.cs
- src/keepass2android-app/LockCloseListActivity.cs
- src/keepass2android-app/LockingClosePreferenceActivity.cs
- src/keepass2android-app/PasswordActivity.cs
- src/keepass2android-app/QuickUnlock.cs
- src/keepass2android-app/SelectCurrentDbActivity.cs
- src/keepass2android-app/app/App.cs
- src/keepass2android-app/services/CopyToClipboardService.cs
- src/keepass2android-app/services/OngoingNotificationsService.cs
on old Android versions when registering receivers (after upgrade to support target sdk 34)
> fix potential crashes

- src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/WebDavStorage.java
This issue seems to depend on server behavior in PROPFIND request. This PR fixes this for these cases.
> Bugfix: Webdav username and password could got lost during file selection

- src/keepass2android-app/EntryEditActivity.cs
- src/keepass2android-app/Resources/values/strings.xml
* show a toast when users without Play services are trying to scan a QR code (#2791)
* show a message informing that built-in Google Drive support is more and more restricted by Google (#2788)
> improve help texts

- src/Kp2aBusinessLogic/Io/BuiltInFileStorage.cs
- src/Kp2aBusinessLogic/Io/JavaFileStorage.cs
- src/Kp2aBusinessLogic/Io/NetFtpFileStorage.cs
- src/Kp2aBusinessLogic/Io/OneDrive2FileStorage.cs
- src/Kp2aBusinessLogic/Io/OneDriveFileStorage.cs
- src/Kp2aBusinessLogic/SelectStorageLocationActivityBase.cs
- src/Kp2aBusinessLogic/Utils/ExceptionUtil.cs
- src/Kp2aBusinessLogic/database/CheckDatabaseForChanges.cs
- src/Kp2aBusinessLogic/database/KdbDatabaseFormat.cs
- src/Kp2aBusinessLogic/database/SynchronizeCachedDatabase.cs
- src/Kp2aBusinessLogic/database/edit/LoadDB.cs
- src/Kp2aBusinessLogic/database/edit/SaveDB.cs
- src/keepass2android-app/CreateNewFilename.cs
- src/keepass2android-app/EntryActivity.cs
- src/keepass2android-app/EntryEditActivity.cs
- src/keepass2android-app/ExportDatabaseActivity.cs
- src/keepass2android-app/FileSelectHelper.cs
- src/keepass2android-app/GeneratePasswordActivity.cs
- src/keepass2android-app/PasswordActivity.cs
- src/keepass2android-app/ShareUrlResults.cs
- src/keepass2android-app/SyncUtil.cs
- src/keepass2android-app/Utils/Util.cs
- src/keepass2android-app/app/App.cs
- src/keepass2android-app/fileselect/FileChooserFileProvider.cs
- src/keepass2android-app/fileselect/FileSelectActivity.cs
- src/keepass2android-app/search/SearchResults.cs
- src/keepass2android-app/search/SearchTotpResults.cs
- src/keepass2android-app/services/AutofillBase/AutofillServiceBase.cs
- src/keepass2android-app/settings/AppSettingsActivity.cs
- src/keepass2android-app/settings/ExportKeyfileActivity.cs
Extract original message when showing "Java exception messages" consistently. Improve error handling in deprecated OneDrive API stub and avoid crash by no-longer throwing in Main-thread methods.
Closes #2837
> Improve error reporting and fix crash

- src/java/JavaFileStorage/app/src/main/java/keepass2android/javafilestorage/WebDavStorage.java
- src/keepass2android-app/Resources/values-cs/strings.xml
- src/keepass2android-app/Resources/values-da/strings.xml
- src/keepass2android-app/Resources/values-de/strings.xml
- src/keepass2android-app/Resources/values-el/strings.xml
- src/keepass2android-app/Resources/values-fr/strings.xml
- src/keepass2android-app/Resources/values-it/strings.xml
- src/keepass2android-app/Resources/values-pt-rBR/strings.xml
- src/keepass2android-app/Resources/values-sk/strings.xml
- src/keepass2android-app/Resources/values-zh/strings.xml
- src/keepass2android-app/Resources/values/strings.xml
- src/keepass2android-app/Resources/xml/pref_app_file_handling.xml
- src/keepass2android-app/app/App.cs
- fix issue with non-chunked upload which could lead to invalid data being uploaded
- disable chunked upload by default and explain that it is not the same as Nextcloud chunking.
- simplify http/cleartext check
- improve preferences by adding a checkbox instead of 0/non-0
closes #3024, #2987
> Fix issues with Webdav connection:
